### ISSUE TITLE
Business App Starter Company Logos in Accounts Page view bug

### ISSUE THREAD

**Issue by ankurshrestha** [vaadin/starters#6] opened 2019-11-14 21:42 UTC
Bug in Business starter app. Screen session: https://share.vidyard.com/watch/W1GnsAxoQaS892fAptTGVJ?

To reproduce the bug:

1. Click on Accounts tab
2. Click on any account
3. Click on Payments tab
4. Click back on Accounts tab (bug appears)

Browser: Version 78.0.3904.97 (Official Build) (64-bit), MacOS

**Comment by anasmi** [comment] 2020-05-18 08:14
Hi,

unfortunately, I am not able to reproduce the issue anymore. 

I will close this issue due to that, but, please, let us know if it's still an issue for you and how it can be reproduced. Then we will take another look into it

**Closed by anasmi** 2020-05-18 08:14 UTC
