### ISSUE TITLE
Problem creating new starter List pro

### ISSUE THREAD

**Issue by batuzai25** [vaadin/starters#36] opened 2021-11-22 21:54 UTC
I was unable to download my application from start.vaadin.com.

This was the configuration used:

```json
{
  "applicationConfiguration": {
    "projectName": "My App",
    "groupId": "com.example.application",
    "vaadinVersion": "lts",
    "codeGeneration": "JAVA",
    "dockerConfiguration": false,
    "kubernetesConfiguration": false,
    "alwaysGenerateBackend": false,
    "javaVersion": 8,
    "access": "PUBLIC",
    "experimentalFeatures": [],
    "git": true,
    "generatedProjectId": "1c4175d8-fe17-4226-86d1-7c830fe33cbb"
  },
  "theme": {
    "componentStyles": {
      "vaadin-button": [
        "\n:host(:not([theme~=\"tertiary\"])) {\n  background-image: linear-gradient(var(--lumo-tint-5pct), var(--lumo-shade-5pct));\n  box-shadow: inset 0 0 0 1px var(--lumo-contrast-20pct);\n}\n:host(:not([theme~=\"tertiary\"]):not([theme~=\"primary\"]):not([theme~=\"error\"]):not([theme~=\"success\"])) {\n  color: var(--lumo-body-text-color);\n}\n:host([focus-ring]:not([theme~=\"tertiary\"])) {\n  box-shadow: 0 0 0 2px var(--lumo-primary-color-50pct), inset 0 0 0 1px var(--lumo-primary-color);\n}\n:host([focus-ring][theme~=\"primary\"]) {\n  box-shadow: 0 0 0 2px var(--lumo-primary-color-50pct), inset 0 0 0 1px var(--lumo-primary-contrast-color);\n}\n:host([theme~=\"primary\"]) {\n  text-shadow: 0 -1px 0 var(--lumo-shade-20pct);\n}"
      ]
    },
    "variant": "light",
    "styles": ""
  },
  "views": [
    {
      "name": "Main",
      "type": "no-main-layout",
      "route": "",
      "entityId": -1,
      "children": [
        {
          "name": "Hello World",
          "type": "list-view",
          "route": "hello",
          "entityId": -1,
          "children": [],
          "generateTestData": true,
          "generateUrlTemplate": false,
          "icon": "la la-th",
          "id": 7
        },
        {
          "name": "About",
          "type": "empty-view",
          "route": "about",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false,
          "icon": "la la-file",
          "id": 8
        }
      ],
      "generateTestData": false,
      "generateUrlTemplate": false,
      "id": 6
    }
  ],
  "entities": []
}
```

**Comment by batuzai25** [comment] 2021-11-22 21:55
Problem creating new starter List pro

**Comment by tarekoraby** [comment] 2021-11-23 11:39
The issue is now fixed. 
Thank you @batuzai25 for reporting!

**Closed as completed by tarekoraby** 2021-11-23 11:39 UTC
